name: build-replit

on:
  workflow_dispatch:
jobs:
  build-ubuntu-2004-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
      - name: Install libgd
        run: |
          sudo apt remove -y libgd3 nginx
          sudo apt install -y libgd-dev
      - name: Install libgeoip
        run: |
          sudo apt install -y libgeoip-dev
      - name: Configure nginx
        run: >
          cd nginx;
          ./auto/configure --http-client-body-temp-path=/home/runner/proxy/cache/client_body --http-proxy-temp-path=/home/runner/proxy/cache/proxy --http-fastcgi-temp-path=/home/runner/proxy/cache/fastcgi --http-uwsgi-temp-path=/home/runner/proxy/cache/uwsgi --http-scgi-temp-path=/home/runner/proxy/cache/scgi;
          cd ..;
      - name: Configure pcre2
        run: |
          cd pcre2;
          ./autogen.sh;
          cd ..;
      - name: Configure libressl
        run: |
          cd libressl;
          ./autogen.sh;
          cd ..;
      - name: Compile nginx
        run: |
          cd nginx;
          make -j$(nproc);
          cd ..;
      - name: Strip binary
        run: |
          strip --strip-unneeded nginx/objs/nginx;
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'nginx-ubuntu-2004-amd64-${{github.sha}}'
          path: nginx/objs/nginx
